import { useQuery } from "convex/react";
import { Link } from "react-router";
import { api } from "../../convex/_generated/api";
import { Icon } from "../components/Icon";
import { dateTime } from "../lib/format";

const REPO = "https://github.com/winsznx/kept";

const GLANCE: { kicker: string; title: string; body: string; href: string; icon: "verify" | "detect" | "globe" | "lock" | "evidence" | "flask" | "email" | "hash"; tone: string }[] = [
  { kicker: "Live · production", title: "End-to-end run passed", body: "Forwarded signup → OpenAI extraction → month-22 drift → AgentMail case and reply → verified on bill 23.", href: "/proof/run/live-loop-2026-09-22", icon: "verify", tone: "is-ok" },
  { kicker: "Independent verifier", title: "11 / 11 invariants pass", body: "Re-derived from corpus, cached model outputs and pure decision code.", href: `${REPO}/blob/main/evidence/verification.md`, icon: "lock", tone: "is-ok" },
  { kicker: "Deterministic · fixture", title: "Month 22 detected, 23–24 not counted", body: "Missing $18.75, promised remaining $56.25. 0 of 5 provider claims marked verified.", href: `${REPO}/blob/main/evidence/campaign-report.md`, icon: "detect", tone: "is-bad" },
  { kicker: "Control", title: "Benign rewrites ignored: 8 / 8", body: "Material page changes caught 8 / 8. First scoring 6 / 8 is published too.", href: `${REPO}/blob/main/evidence/campaign-report.md`, icon: "globe", tone: "is-soft" },
  { kicker: "Refusal", title: "Correct abstention 10 / 10", body: "Marketplace seller vs retailer policy, region mismatch, ranges, total-only bills, prompt injection.", href: `${REPO}/blob/main/evidence/campaign-report.md`, icon: "flask", tone: "is-warn" },
  { kicker: "Guards", title: "Security and duplicate-send guards", body: "Cross-user isolation, storage claims, signed webhooks, idempotent sends, demo throttles. Tests plus threat model.", href: `${REPO}/blob/main/docs/THREAT_MODEL.md`, icon: "hash", tone: "is-soft" },
  { kicker: "Sponsors", title: "Four load-bearing roles", body: "Convex state and realtime, Firecrawl captures, OpenAI extraction, AgentMail inbox and thread. Ablation measured.", href: `${REPO}/blob/main/evidence/sponsor-ablation.md`, icon: "email", tone: "is-soft" },
  { kicker: "Evidence fidelity", title: "68 / 68 decisions source-bound", body: "Every auto-decided term quotes the source text containing its value.", href: `${REPO}/blob/main/evidence/campaign-report.md`, icon: "evidence", tone: "is-soft" },
];

export default function Proof() {
  const runs = useQuery(api.proof.listRuns);
  return (
    <div className="container page stack-lg">
      <div className="page-head" style={{ marginBottom: 0 }}>
        <span className="eyebrow">
          <Icon name="verify" size={15} /> Proof
        </span>
        <h1>Don’t trust the narration. Inspect the runs.</h1>
        <p>
          Persisted, sanitized records of real runs, straight from Convex. The product itself is the <Link to="/demo" style={{ textDecoration: "underline" }}>demo</Link> and the signed-in app.
        </p>
      </div>
      <section className="stack" aria-labelledby="glance-title">
        <h2 id="glance-title" className="section-title">
          <Icon name="verify" size={18} /> At a glance
        </h2>
        <div className="grid-2">
          {GLANCE.map((g) => (
            <a key={g.title} href={g.href} className="card row" style={{ alignItems: "flex-start", gap: 14, flexWrap: "nowrap" }} {...(g.href.startsWith("http") ? { target: "_blank", rel: "noopener noreferrer" } : {})}>
              <span className={`icon-tile ${g.tone}`}>
                <Icon name={g.icon} size={19} />
              </span>
              <span style={{ minWidth: 0 }}>
                <span className="label" style={{ display: "block" }}>
                  {g.kicker}
                </span>
                <strong style={{ display: "block", fontSize: 17, letterSpacing: "-0.01em", marginTop: 2 }}>{g.title}</strong>
                <span className="small muted" style={{ display: "block", marginTop: 4 }}>
                  {g.body}
                </span>
              </span>
            </a>
          ))}
        </div>
        <p className="small faint">
          Numbers come from committed artifacts in <a href={`${REPO}/tree/main/evidence`} style={{ textDecoration: "underline" }}>evidence/</a>, generated by scripts, not typed by hand.
        </p>
      </section>

      <section className="stack">
        <h2 className="section-title">
          <Icon name="record" size={18} /> Inspectable runs
        </h2>
        {runs === undefined ? <p role="status">Loading…</p> : null}
        {runs?.length === 0 ? <p className="muted">No runs recorded yet.</p> : null}
        <ul className="item-list">
          {runs?.map((r) => (
            <li key={r.slug}>
              <Link to={`/proof/run/${r.slug}`} className="item-row" style={{ gridTemplateColumns: "44px minmax(0,1fr) auto" }}>
                <span className="icon-tile is-ok">
                  <Icon name="verify" size={19} />
                </span>
                <div style={{ minWidth: 0 }}>
                  <h3>{r.title}</h3>
                  <div className="meta mono">
                    {dateTime(r.createdAt)} · payload sha256 {r.payloadSha256.slice(0, 16)}…
                  </div>
                </div>
                <span className="row">
                  <span className={`badge ${r.kind === "LIVE" ? "tone-ok" : "tone-neutral"}`}>{r.kind}</span>
                  <Icon name="chevronRight" size={18} className="faint" />
                </span>
              </Link>
            </li>
          ))}
        </ul>
      </section>
      <section className="stack">
        <h2 className="section-title">
          <Icon name="evidence" size={18} /> What’s measured and where
        </h2>
        <ul className="prose" style={{ paddingLeft: 20 }}>
          <li>
            Deterministic reconciliation, evidence binding, verified-fix logic and guards: unit and Convex tests in <a href={`${REPO}/tree/main/tests`}>tests/</a>.
          </li>
          <li>
            Evaluation methodology, registered before any campaign ran: <a href={`${REPO}/blob/main/docs/EVALUATION.md`}>docs/EVALUATION.md</a>.
          </li>
          <li>
            Build log: <a href={`${REPO}/blob/main/hackathon.md`}>hackathon.md</a>.
          </li>
        </ul>
        <p className="small muted">Campaign results appear here only after they’ve been run and written to the repo’s evidence folder.</p>
      </section>
    </div>
  );
}
