import { chromium } from "@playwright/test";

const base = process.argv[2] ?? "http://localhost:5173";
const browser = await chromium.launch();
const page = await browser.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
const email = `smoke-${Date.now()}@example.test`;
await page.goto(`${base}/signup`);
await page.getByLabel("Email").fill(email);
await page.getByLabel("Password").fill("correct-horse-9");
await page.getByRole("button", { name: /create your kept account/i }).click();
await page.getByRole("heading", { name: "My protected plans" }).waitFor({ timeout: 30000 });
console.log("signup reached /app");
await page.getByRole("link", { name: "Protect a plan" }).first().click();
await page.getByLabel(/Provider/).fill("Smoke Test Carrier");
await page.getByRole("button", { name: "Continue to evidence" }).click();
await page.getByRole("heading", { name: "Add evidence" }).waitFor({ timeout: 20000 });
console.log("created item, deep link:", new URL(page.url()).pathname);
await page.reload();
await page.getByRole("heading", { name: "Add evidence" }).waitFor({ timeout: 20000 });
console.log("item deep route survives reload");
await page.getByRole("button", { name: "Sign out" }).click();
await page.waitForTimeout(800);
await page.goto(`${base}/app`);
await page.waitForURL("**/login", { timeout: 10000 });
console.log("signed-out /app redirects to /login");
console.log("page errors:", errors.length);
await browser.close();
process.exit(errors.length ? 1 : 0);
